SPECIAL_TYPE_MAPPINGS = {
    ('NON-CINTAS', 'NON-CINTAS'): 'THIRD PARTY',
    ('CC', 'US DC'): '0G59',
    ('MFG', 'US DC'): '0G59',
    ('NON-CINTAS', 'US DC'): '0G59',
    ('NON-CINTAS', 'CA DC'): '0G59',
    ('US DC', 'CA DC'): '0G59',
    ('CA DC', 'CC'): "DOESN'T EXIST",
    ('CA DC', 'FC'): "DOESN'T EXIST",
    ('CA DC', 'FL'): "DOESN'T EXIST",
    ('CA DC', 'MFG'): "DOESN'T EXIST",
    ('CA DC', 'MM'): "DOESN'T EXIST",
    ('CC', 'CA DC'): "DOESN'T EXIST",
    ('CC', 'FAS DC'): "DOESN'T EXIST",
    ('CC', 'FC'): "DOESN'T EXIST",
    ('CC', 'FL'): "DOESN'T EXIST",
    ('CC', 'LC'): "DOESN'T EXIST",
    ('CC', 'MM'): "DOESN'T EXIST",
    ('CC', 'NON-CINTAS'): "DOESN'T EXIST",
    ('FAS DC', 'CC'): "DOESN'T EXIST",
    ('FAS DC', 'MFG'): "DOESN'T EXIST",
    ('FC', 'CA DC'): "DOESN'T EXIST",
    ('FC', 'CC'): "DOESN'T EXIST",
    ('FC', 'MFG'): "DOESN'T EXIST",
    ('FL', 'CA DC'): "DOESN'T EXIST",
    ('FL', 'CC'): "DOESN'T EXIST",
    ('FL', 'MFG'): "DOESN'T EXIST",
    ('LC', 'CC'): "DOESN'T EXIST",
    ('LC', 'MFG'): "DOESN'T EXIST",
    ('MFG', 'CA DC'): "DOESN'T EXIST",
    ('MFG', 'FAS DC'): "DOESN'T EXIST",
    ('MFG', 'FC'): "DOESN'T EXIST",
    ('MFG', 'FL'): "DOESN'T EXIST",
    ('MFG', 'LC'): "DOESN'T EXIST",
    ('MFG', 'MM'): "DOESN'T EXIST",
    ('MFG', 'NON-CINTAS'): "DOESN'T EXIST",
    ('MM', 'CC'): "DOESN'T EXIST",
    ('MM', 'MFG'): "DOESN'T EXIST",
    ('US DC', 'CC'): "DOESN'T EXIST",
    ('US DC', 'MFG'): "DOESN'T EXIST"
}

#Coding Matrix for Origin and Destination
Coding_Matrix = {
    ("CA DC", 'CA DC'): "DESTINATION",
    ('CA DC', 'FAS DC'): "DESTINATION",
    ('CA DC', 'LC'): "DESTINATION",
    ('CA DC', 'US DC'): "DESTINATION",
    ('CC', 'CC'): "DESTINATION",
    ('CC', 'MFG'): "DESTINATION",
    ('FAS DC', 'FAS DC'): "DESTINATION",
    ('FC', 'FAS DC'): "DESTINATION",
    ('FC', 'FC'): "DESTINATION",
    ('FC', 'LC'): "DESTINATION",
    ('FL', 'FAS DC'): "DESTINATION",
    ('FL', 'FL'): "DESTINATION",
    ('FL', 'LC'): "DESTINATION",
    ('LC', 'LC'): "DESTINATION",
    ('LC', 'CA DC'): "DESTINATION",
    ('LC', 'FAS DC'): "DESTINATION",
    ('LC', 'FC'): "DESTINATION",
    ('LC', 'FL'): "DESTINATION",
    ('MFG', 'MFG'): "DESTINATION",
    ('MFG', 'CC'): "DESTINATION",
    ('MM', 'FAS DC'): "DESTINATION",
    ('MM', 'FC'): "DESTINATION",
    ('MM', 'FL'): "DESTINATION",
    ('MM', 'LC'): "DESTINATION",
    ('MM', 'MM'): "DESTINATION",
    ('MM', 'US DC'): "DESTINATION",
    ('NON-CINTAS', 'CC'): "DESTINATION",
    ('NON-CINTAS', 'FAS DC'): 'DESTINATION',
    ('NON-CINTAS', 'FC'): 'DESTINATION',
    ('NON-CINTAS', 'FL'): 'DESTINATION',
    ('NON-CINTAS', 'LC'): 'DESTINATION',
    ('NON-CINTAS', 'MFG'): 'DESTINATION',
    ('NON-CINTAS', 'MM'): 'DESTINATION',
    ('US DC', 'US DC'): 'DESTINATION',
    ('CA DC', 'NON-CINTAS'): 'ORIGIN',
    ('FAS DC', 'FC'): 'ORIGIN',
    ('FAS DC', 'FL'): 'ORIGIN',
    ('FAS DC', 'CA DC'): 'ORIGIN',
    ('FAS DC', 'LC'): 'ORIGIN',
    ('FAS DC', 'MM'): 'ORIGIN',
    ('FAS DC', 'NON-CINTAS'): 'ORIGIN',
    ('FAS DC', 'US DC'): 'ORIGIN',
    ('FC', 'FL'): 'ORIGIN',
    ('FC', 'MM'): 'ORIGIN',
    ('FC', 'NON-CINTAS'): 'ORIGIN',
    ('FC', 'US DC'): 'ORIGIN',
    ('FL', 'FC'): 'ORIGIN',
    ('FL', 'MM'): 'ORIGIN',
    ('FL', 'NON-CINTAS'): 'ORIGIN',
    ('FL', 'US DC'): 'ORIGIN',
    ('LC', 'MM'): 'ORIGIN',
    ('LC', 'NON-CINTAS'): 'ORIGIN',
    ('LC', 'US DC'): 'ORIGIN',
    ('MM', 'CA DC'): 'ORIGIN',
    ('MM', 'NON-CINTAS'): 'ORIGIN',
    ('US DC', 'FAS DC'): 'ORIGIN',
    ('US DC', 'FC'): 'ORIGIN',
    ('US DC', 'FL'): 'ORIGIN',
    ('US DC', 'LC'): 'ORIGIN',
    ('US DC', 'CA DC'): 'ORIGIN',
    ('US DC', 'MM'): 'ORIGIN',
    ('US DC', 'NON-CINTAS'): 'ORIGIN'
}
